### ISSUE TITLE
License (GPL?)

### ISSUE THREAD

**Issue by yuki-koyama** [ryichando/shiokaze#1]
Hello, thank you for this really great library.

I found the following files seem to be licensed under GPL according to their header comments:

- `shiokaze/launcher/src/main.cpp`
- `shiokaze/src/core/configuration.cpp`

But is this intended? I think most other files are licensed under MIT so I guess this is just a miswriting.

**Comment by ryichando** [comment]
Thanks for pointing this out! It is completely miswriting and they are all fixed now.
