### ISSUE TITLE
Error: undefined symbol: glfwGetWindowContentScale

### ISSUE THREAD

**Issue by goofoo** [ryichando/shiokaze#3]
Building project and launch ok, but when move mouse program crash with error:

./build/launcher/launcher: symbol lookup error: build/src/ui/libshiokaze_ui.so: undefined symbol: glfwGetWindowContentScale

**Comment by ryichando** [comment]
Please provide your OS and running command. I'll take a look.

**Comment by goofoo** [comment]
os ubuntu 18.04, running command: 
./run Target=macliquid2
./run Target=macliquid3 Log=log_waterdrop
same error
i clone repo and compile again - nothing good

**Comment by ryichando** [comment]
Thank you for reporting the bug. It should be fixed now. Please update your copy of shiokaze.

**Comment by goofoo** [comment]
All working fine. Closed.
