### ISSUE TITLE
A Practical Octree Liquid Simulator with Adaptive Surface Resolution has been implemented on this Framework, and could you tell me where it is?

### ISSUE THREAD

**Issue by for-heart-peace** [ryichando/shiokaze#4]
Hello, Dr Ryoichi Ando
I am learning  your research ’A Practical Octree Liquid Simulator with Adaptive Surface Resolution‘，and I could not find the research int the project. I search 'octree' in the project. Unfortunately, I didn't find it in the project and the SHKZ( https://ryichando.graphics/shiokaze/index.html)

**Comment by ryichando** [comment]
Thank you for pointing this out! I have just uploaded all the codes to this repository. Here’s a complete guide to run our code:

1: Create a free account on gitpod (http://gitpod.io/)
2. Make a copy of repository of https://github.com/ryichando/shiokaze
3. Go to terminal, and run “./waf configure; ./waf"
4. Run "./run Target=macoctreeliquid3 Log=log_waterdrop RenderWireframe=Yes"

Now you should be able to see rendered images at log_waterdrop/mesh_img and log_waterdrop/wireframe_img like the one attached.
<img width="512" alt="shiokaze-gitpod" src="https://user-images.githubusercontent.com/40781683/173459102-d29a010d-14f1-4bbc-b23b-5ac409a38cb5.png">
